### ISSUE TITLE
有考虑升级 ts 版本到 4.7.x 以上吗？

### ISSUE THREAD

**Issue by ddzyan** [midwayjs/mwcc#20]
看最近有更新过一个版本 ts 的版本支持到了 4.6.x 以上，后面有打算升级到 4.7.x 以上吗，现在在使用的时候遇到编译报错 1005 语法不支持的问题，本地用 4.7.x 版本的 ts 编译就可以过，但是还是有些奇怪的问题。
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/9130123/181694945-6fd9200d-090c-4128-b834-521528a7b91a.png">

**Comment by czy88840616** [comment]
后面mwcc会废弃，cli会直接用ts-node

**Comment by ddzyan** [comment]
好吧，看来现在只能自己用 tsc 编译，然后开始优化了
