### ISSUE TITLE
内置 TypeScript Path Alias 的支持

### ISSUE THREAD

**Issue by Lxxyx** [midwayjs/mwcc#3]
相关 issue: https://github.com/midwayjs/midway/issues/685

希望支持：
1. 纯函数项目的 path alias
2. 一体化项目的 path alias

Next.js 实现：https://nextjs.org/docs/advanced-features/module-path-aliases

**Comment by czy88840616** [comment]
应用的是不是也是一起支持了

**Comment by Lxxyx** [comment]
@czy88840616 目前只支持构建时使用，开发期的得等 mwcc/register 功能。

因此应用可能在开发期还得引入 tsconfig-paths，构建时可以使用 mwcc（不过应用应该直接使用 tsconfig-paths 就行了）

**Comment by czy88840616** [comment]
现在应用构建用tsconfig-path好像不行

**Comment by Lxxyx** [comment]
等提案合并后统一看看各个模式下的兼容吧
